Яковенко Юлия
urfu-2017/webdev-task-1 pull request #11
Opened 2018-03-06 11:32 UTC by Ftlka

2018-03-06 11:32 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-11 15:45 UTC, Superilya requested changes

2018-03-11 15:45 UTC, Superilya commented on index.js
> +    res.locals.category = req.path.substr(1, req.path.indexOf('&') - 1) || req.path.substr(1);
воу воу, req.params.category

2018-03-11 15:45 UTC, Superilya commented on middlewares/common-data.js
> +    const categories = ['business', 'entertainment', 'general', 'health',
эти данные не нужно докидывать в request можно сделать файл config или каталог, не важно и от туда их require'ить :)

2018-03-11 15:45 UTC, Superilya commented on middlewares/date-format.js
> +module.exports = function formatDate(date) {
это не middleware, да и файл как я понимаю лишний

2018-03-11 15:45 UTC, Superilya commented on middlewares/news-fetcher.js
> +    const url = baseUrl + req.path.substr(1) + '&country=' + country + keyString;
собирать так урл плохо, используй модуль url или query-string если надо (https://www.npmjs.com/package/query-string)

2018-03-11 15:45 UTC, Superilya commented on middlewares/weather-middleware.js
> +const fetch = require('node-fetch');
👍

2018-03-11 15:45 UTC, Superilya commented on middlewares/weather-middleware.js
> +        url = baseUrl + `location/search/?lattlong=${lat},${lon}`;
url

2018-03-11 15:45 UTC, Superilya commented on middlewares/weather-middleware.js
> +    if (lat && !Number.isNaN(lat) && lon && !Number.isNaN(lon)) {
зачем тут проверка на NaN `Boolean(NaN) === false`, я конечно плохо понимаю на сколько сильно вам можно использовать библиотеки, но lodash, очень хорошо смотрится на сервере

2018-03-11 15:45 UTC, Superilya commented on middlewares/weather-middleware.js
> +    oldArray.forEach(element => {
```
if (isDate) {
    oldArray.forEach(element => {
        elements.push(formatDate(element[field]));
    });
} else {
    oldArray.forEach(element => {
        elements.push(parseInt(element[field]));
    });
}
```
1
допустим в массиве 100 элементов
было: цикл из 100 итераций + 100 ифов
стало: 1 иф + 100 итераций
profit!
2
функция которая в зависимости от флага меняет смоё поведение на половину, это 2 функции, там где ты её вызываешь 
`getInfo(weather.consolidated_weather, 'applicable_date', true)`
 при таком подходе функция будет менять своё поведение в рантайме, а если ты сделаешь 2 функции то задашь поведение на уровне разработки. На самом деле v8 так или иначе за тебя в памяти сделает 2 функции, но это должна сделать ты.
3
Хуже названия getInfo только getData, разбиение на 2 функции тебе с этим поможет

2018-03-11 15:47 UTC, Superilya commented on middlewares/common-data.js
> +    const categories = ['business', 'entertainment', 'general', 'health',
всё что не изменяет req или res не middleware

2018-03-11 15:49 UTC, Superilya commented on middlewares/weather-middleware.js
> +    const json = await response.json();
ну может ты не знаешь
`return await response.json();`

2018-03-11 15:54 UTC, Superilya commented on middlewares/news-fetcher.js
> +    request(url, (err, response, body) => {
надо ~~взять нормальный node-fetch~~ выбрать что то одно request или node-fetch

2018-03-11 16:14 UTC, Superilya commented
Мне вообще не нравится как построен проект, не знаю на сколько я могу этого требовать (я узнаю), но mvc тут нет даже в самом простом виде. Для работы с api новостей и погоды нужно сделать модели. Модель представляет собой класс инстанс которого создаётся в контроллере, там же используются его методы, получчаются данные из модели и отдаются во view (в данном случае render). В общем случае контроллер должен выглядеть так
```
const controller = async (req, res, next) => {
    const weather = new WeatherModel(req);
    const weatherData = await weather.get();

    await res.render('category', weatherData);
}
```

Цитата 
```
Обратите внимание, что информация о погоде используется сразу на двух страницах, и было бы очень круто, если бы этот код был написан 1 раз.
```
тонкий намёк на базовую модель, методы которой могут переиспользовать WeatherModel и NewsModel

Работа на прямую с контентом в мидлварах плохо, потому что эта логика обычно сильно растёт, а в таком формате её расширять сложно.

2018-03-13 12:29 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-13 16:11 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-13 16:40 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-14 03:43 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-14 11:02 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-14 15:36 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-14 15:48 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-14 15:51 UTC, closed without merging