Роман Рыженко
urfu-2017/webdev-task-1 pull request #21
Opened 2018-03-07 16:26 UTC by WBDiamond

Роман Рыженко

2018-03-07 16:27 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-03-07 16:40 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-03-07 16:42 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-03-07 16:55 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-03-07 17:01 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-03-07 17:05 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-03-07 17:10 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-03-07 17:15 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-03-07 17:25 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-12 17:46 UTC, noveogroup-amorgunov requested changes
1. Следить за названиями коммитов
2. Если я в query укажи не город (например 12345), то нода выкинет ошибку: `(node:85900) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): RangeError: Invalid status code: undefined`
3. Изменить файл readme. Указать, что нужно сделать для запуска приложения (например выполнить npm install и npm start), а задание можно вынести просто ссылкой
4. Если останется время, можно посмотреть на eslint конфиг от airbnb (https://github.com/airbnb/javascript, https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb) вместо хрюндель-конфига, так как он сам будет отлавливать множество стилистических ошибок (например использования const вместо let, если переменная не изменяется, сокращенная запись объекта, лишние пробелы итд)
5. Давай немного стили поинтереснее сделаем, сейчас визуально выглядит плохо

2018-03-12 17:46 UTC, noveogroup-amorgunov commented on .idea/encodings.xml
> +<?xml version="1.0" encoding="UTF-8"?>
папку .idea добавить в .gitignore

2018-03-12 17:46 UTC, noveogroup-amorgunov commented on package.json
>      "test": "npm run lint && mocha tests/*.js"
команда npm start не работает

2018-03-12 17:46 UTC, noveogroup-amorgunov commented on app/controllers/errors.js
> +'use strict';
Зачем в каждом файле писать 'use strict;'?

2018-03-12 17:46 UTC, noveogroup-amorgunov commented on app/controllers/main.js
> +        const data = Object.assign({ widget, categories }, res.locals);
если версия ноды > 8.7, то можно использовать object spread operator: `const data = { ...res.locals, widget, categories };`

2018-03-12 17:46 UTC, noveogroup-amorgunov commented on app/controllers/main.js
> +        res.render('index', data);
можно так же передавать title страницы в data

2018-03-12 17:46 UTC, noveogroup-amorgunov commented on app/controllers/main.js
> +        Widget.build(req.query.query),
Если widget - это погодный виджет, то так его и назвать - WeatherWidget.
build я перевожу как строить. Лучше использовать название fetch/get/find (и это название метода использовать для всех моделей)

2018-03-12 17:46 UTC, noveogroup-amorgunov commented on app/controllers/main.js
> +        Category.getCategories(req.query.country)
тут название метода можно сократить до get (и так ясно что получение категорий)

2018-03-12 17:46 UTC, noveogroup-amorgunov commented on app/controllers/main.js
> +        .catch(err => {
.catch поднять на строчку выше `}).catch(err => {`

2018-03-12 17:46 UTC, noveogroup-amorgunov commented on app/controllers/main.js
> +    ]).then(vals => {
используя деструктизацию можно vals заменить на `([widget, categories])`

2018-03-12 17:46 UTC, noveogroup-amorgunov commented on app/controllers/news.js
> +        Article.getArticles(req.query.country, req.query.category)
в js есть прием по передаче параметров в метод в виде одного объекта, если их больше одного. Сразу ясно какой параметр за что отвечает и порядок не важен: News.find({ country, category: req.params.category })

2018-03-12 17:46 UTC, noveogroup-amorgunov commented on app/controllers/news.js
> +exports.news = (req, res) => {
Такие же замечания как и в контроллере main.js

2018-03-12 17:46 UTC, noveogroup-amorgunov commented on app/controllers/news.js
> +        res.locals.nonMain = true;
можно перенести в common-data мидделавар и определять по path главная страница или нет

2018-03-12 17:46 UTC, noveogroup-amorgunov commented on app/index.js
> +module.exports = app;
обычно экспорты делают в конце файла

2018-03-12 17:46 UTC, noveogroup-amorgunov commented on app/index.js
> +    const port = 8080;
порт есть в конфиге, значит тут нужно считывать его из конфига

2018-03-12 17:46 UTC, noveogroup-amorgunov commented on app/index.js
> +app.use((err, req, res, next) => {
вынести миддлевар обработки ошибок в отдельный файл middlewares/handle-errors.js

2018-03-12 17:46 UTC, noveogroup-amorgunov commented on app/middlewares/common-data.js
> +    res.locals.title = 'Weather';
сайт на русском, title на английском

2018-03-12 17:46 UTC, noveogroup-amorgunov commented on app/middlewares/common-data.js
> +    res.locals.staticBasePath = '/';
читать из конфига

2018-03-12 17:46 UTC, noveogroup-amorgunov commented on app/middlewares/common-data.js
> +    res.locals.weatherApiBasePath = 'https://www.metaweather.com/';
вынести в конфиг url

2018-03-12 17:46 UTC, noveogroup-amorgunov commented on app/views/partials/widget.hbs
> +<div class="widget">
исправить названия классов согласно методологии бэм во всех файлах

2018-03-12 17:46 UTC, noveogroup-amorgunov commented on app/models/category.js
> +        this.urlName = urlName;
переименовать в category

2018-03-12 17:46 UTC, noveogroup-amorgunov commented on app/views/index.hbs
> +        <div class="page-wrap">
page-wrapper

2018-03-12 17:46 UTC, noveogroup-amorgunov commented on app/views/news.hbs
> +            {{>  widget}}
лишний пробел

2018-03-12 17:46 UTC, noveogroup-amorgunov commented on app/views/news.hbs
> +<html lang="en">
изменить на ru

2018-03-12 17:46 UTC, noveogroup-amorgunov commented on app/views/index.hbs
> +<html lang="en">
layout вынести в отдельный файл (используется одинаковый в двух местах: тут и в шаблоне news)

2018-03-12 17:46 UTC, noveogroup-amorgunov commented on app/public/wind.svg
> +<?xml version="1.0" encoding="iso-8859-1"?>
прогнать все картинки через https://github.com/svg/svgo

2018-03-12 17:46 UTC, noveogroup-amorgunov commented on app/public/styles.css
> +
лишние переносы строк

2018-03-12 17:46 UTC, noveogroup-amorgunov commented on app/public/business.svg
> +<?xml version="1.0" encoding="iso-8859-1"?>
Картинки для категорий вынести в подкаталог

2018-03-12 17:46 UTC, noveogroup-amorgunov commented on app/models/widget.js
> +                    date: date,
можно использовать сокращенную запись объекта `date,` и ниже temperature

2018-03-12 17:46 UTC, noveogroup-amorgunov commented on app/models/article.js
> +const apiBasePath = 'https://newsapi.org/v2/top-headlines';
вынести в конфиг apiBasePath и apiKey

2018-03-12 17:46 UTC, noveogroup-amorgunov commented on app/models/article.js
> +const request = require('request');
лучше использовать модуль axios - один из топовых модулей по работе с запросами

2018-03-12 17:46 UTC, noveogroup-amorgunov commented on app/models/article.js
> +        request(`${apiBasePath}?country=${country}&category=${category}&apiKey=${apiKey}`,
если использовать аксиос то не нужно оборачивать в промис и не нужно query параметры преобразовывать в строку, будет достаточно написать:

```
axios.get(apiBasePath, { params: { apiKey, category, country } })
```

Аксиос сам преобразует объект в query-строку.

2018-03-12 17:46 UTC, noveogroup-amorgunov commented on app/models/article.js
> +                resolve(articles.articles);
что бы не было такого, переменную можно назвать parsedBody

2018-03-12 17:46 UTC, noveogroup-amorgunov commented on app/models/article.js
> +function getHeadlines(country, category) {
переместить в класс модели, переименовав в _fetch (_ - указывает на то, что метод приватный и за пределами класса использовать нельзя)

2018-03-12 17:46 UTC, noveogroup-amorgunov commented on app/models/category.js
> +const russianCategories = {
нет мультиязычности, не нужно переменные называть с названия языка

2018-03-12 17:46 UTC, noveogroup-amorgunov commented on app/models/category.js
> +    'entertainment': 'Развлечения',
у ключей кавычки не нужны

2018-03-12 17:46 UTC, noveogroup-amorgunov commented on app/models/category.js
> +const russianCategories = {
вместо массива и объекта с категориями достаточно сделать одну переменную:

```
const categories = {
   business: 'Бизнес',
   entertainment: 'Развлечения',
   // ...
};
```
И если понадобится список категорий как массив, то можно использовать `Object.keys(categories)`

2018-03-12 17:46 UTC, noveogroup-amorgunov commented on app/models/widget.js
> +const apiBasePath = 'https://www.metaweather.com/api/location/';
в конфиг вынести

2018-03-12 17:46 UTC, noveogroup-amorgunov commented on app/models/widget.js
> +function getWeatherReport(cityName) {
методы внутрь класса

2018-03-12 17:46 UTC, noveogroup-amorgunov commented on app/models/widget.js
> +                const date = parseInt(splitDate[2]) + ' ' + monthMap[parseInt(splitDate[1])];
форматированную дату можно получить используя метод объекта Date `toLocaleDateString`, либо подключить либу `moment.js`. В первом случае будет достаточно сделать:

```js
const options = { month: 'long', day: 'numeric' };
const date = new Date();
const formattedDate = date.toLocaleDateString('ru-Ru', options); // -> 12 марта
```

2018-03-12 17:46 UTC, noveogroup-amorgunov commented on app/models/widget.js
> +function formatReport(weatherReport) {
можно переименовать просто в format/parse

2018-03-12 17:49 UTC, WBDiamond commented on app/controllers/main.js
> +        const data = Object.assign({ widget, categories }, res.locals);
Я пытался здесь, но линт не давал пройти тест локальный почему-то

2018-03-12 17:53 UTC, WBDiamond commented on app/index.js
> +    const port = 8080;
Это ломает тесты хрюнделя, по коммитам можно увидеть, что я пользовался библиотекой для подгрузки конфига, но пришлось убрать, чтобы реквест прошел

2018-03-12 18:02 UTC, WBDiamond commented on app/index.js
> +    const port = 8080;
Ну видимо просто буду импортить конфиг в модули

2018-03-12 18:08 UTC, WBDiamond commented on app/controllers/errors.js
> +'use strict';
Линтер требует

2018-03-12 18:34 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-03-12 18:38 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-03-12 19:12 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-03-12 19:39 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-12 19:42 UTC, WBDiamond commented on package.json
>      "test": "npm run lint && mocha tests/*.js"
689c8c9

2018-03-12 19:43 UTC, WBDiamond commented on .idea/encodings.xml
> +<?xml version="1.0" encoding="UTF-8"?>
2eeb45a

2018-03-12 19:43 UTC, WBDiamond commented on app/controllers/main.js
> +        res.render('index', data);
3d8e8bb

2018-03-12 20:07 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-12 20:08 UTC, WBDiamond commented on app/controllers/main.js
> +        Widget.build(req.query.query),
4fa3a9a

2018-03-12 20:08 UTC, WBDiamond commented on app/controllers/main.js
> +        Category.getCategories(req.query.country)
4fa3a9a

2018-03-12 20:08 UTC, WBDiamond commented on app/views/news.hbs
> +            {{>  widget}}
4fa3a9a

2018-03-13 07:23 UTC, WBDiamond commented
А дедлайн в четверг?

2018-03-13 07:26 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-13 07:29 UTC, WBDiamond commented on app/controllers/errors.js
> +'use strict';
Поставил новый линт, щас буду все фиксить

2018-03-13 07:29 UTC, WBDiamond commented on app/controllers/main.js
> +        .catch(err => {
a745f4a

2018-03-13 07:32 UTC, WBDiamond commented on app/models/category.js
> +    'entertainment': 'Развлечения',
a745f4a

2018-03-13 07:33 UTC, WBDiamond commented on app/controllers/errors.js
> +'use strict';
a745f4a

2018-03-13 07:40 UTC, noveogroup-amorgunov commented
Ага

2018-03-13 08:07 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-13 08:08 UTC, WBDiamond commented on app/controllers/news.js
> +        res.locals.nonMain = true;
f93a45b

2018-03-13 08:08 UTC, WBDiamond commented on app/controllers/news.js
> +exports.news = (req, res) => {
f93a45b

2018-03-13 08:08 UTC, WBDiamond commented on app/controllers/news.js
> +        Article.getArticles(req.query.country, req.query.category)
f93a45b

2018-03-13 08:08 UTC, WBDiamond commented on app/controllers/main.js
> +    ]).then(vals => {
f93a45b

2018-03-13 08:13 UTC, WBDiamond commented on app/controllers/main.js
> +        const data = Object.assign({ widget, categories }, res.locals);
f93a45b

2018-03-13 08:28 UTC, noveogroup-amorgunov commented
@WBDiamond Напиши как код рефакторинг закончишь

2018-03-13 08:30 UTC, WBDiamond commented
@noveogroup-amorgunov сюда же написать?

2018-03-13 08:35 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-13 08:36 UTC, WBDiamond commented on app/index.js
> +module.exports = app;
9698edb

2018-03-13 08:36 UTC, WBDiamond commented on app/index.js
> +    const port = 8080;
9698edb

2018-03-13 08:36 UTC, WBDiamond commented on app/index.js
> +app.use((err, req, res, next) => {
9698edb

2018-03-13 08:36 UTC, WBDiamond commented on app/middlewares/common-data.js
> +    res.locals.staticBasePath = '/';
9698edb

2018-03-13 08:36 UTC, WBDiamond commented on app/middlewares/common-data.js
> +    res.locals.weatherApiBasePath = 'https://www.metaweather.com/';
9698edb

2018-03-13 08:37 UTC, WBDiamond commented on app/middlewares/common-data.js
> +    res.locals.title = 'Weather';
3d8e8bb

2018-03-13 09:25 UTC, noveogroup-amorgunov commented
@WBDiamond да, можно прямо здесь

2018-03-13 09:50 UTC, WBDiamond commented on app/views/index.hbs
> +<html lang="en">
c05c94d

2018-03-13 09:50 UTC, WBDiamond commented on app/views/news.hbs
> +<html lang="en">
c05c94d

2018-03-13 09:50 UTC, WBDiamond commented on app/views/index.hbs
> +        <div class="page-wrap">
c05c94d

2018-03-13 09:51 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-13 10:02 UTC, WBDiamond commented on app/views/partials/widget.hbs
> +<div class="widget">
@noveogroup-amorgunov во всех шаблонах или по js-файлам тоже пройтись?

2018-03-13 12:47 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-03-13 12:48 UTC, WBDiamond commented on app/models/widget.js
> +function formatReport(weatherReport) {
e137e9e

2018-03-13 12:48 UTC, WBDiamond commented on app/models/widget.js
> +                const date = parseInt(splitDate[2]) + ' ' + monthMap[parseInt(splitDate[1])];
e137e9e

2018-03-13 12:48 UTC, WBDiamond commented on app/models/widget.js
> +function getWeatherReport(cityName) {
e137e9e

2018-03-13 12:49 UTC, WBDiamond commented on app/models/widget.js
> +const apiBasePath = 'https://www.metaweather.com/api/location/';
e137e9e

2018-03-13 12:49 UTC, WBDiamond commented on app/models/category.js
> +const russianCategories = {
e137e9e

2018-03-13 12:49 UTC, WBDiamond commented on app/models/article.js
> +function getHeadlines(country, category) {
e137e9e

2018-03-13 12:49 UTC, WBDiamond commented on app/models/article.js
> +                resolve(articles.articles);
e137e9e

2018-03-13 12:50 UTC, WBDiamond commented on app/models/article.js
> +        request(`${apiBasePath}?country=${country}&category=${category}&apiKey=${apiKey}`,
e137e9e

2018-03-13 12:51 UTC, WBDiamond commented on app/models/article.js
> +const request = require('request');
e137e9e

2018-03-13 12:51 UTC, WBDiamond commented on app/models/article.js
> +const apiBasePath = 'https://newsapi.org/v2/top-headlines';
e137e9e

2018-03-13 12:52 UTC, WBDiamond commented on app/models/widget.js
> +                    date: date,
e137e9e

2018-03-13 13:07 UTC, WBDiamond commented on app/models/category.js
> +        this.urlName = urlName;
e137e9e

2018-03-13 14:06 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-13 14:06 UTC, WBDiamond commented on app/public/wind.svg
> +<?xml version="1.0" encoding="iso-8859-1"?>
fe5e370

2018-03-13 14:07 UTC, WBDiamond commented on app/public/styles.css
> +
fe5e370

2018-03-13 14:07 UTC, WBDiamond commented on app/public/business.svg
> +<?xml version="1.0" encoding="iso-8859-1"?>
fe5e370

2018-03-13 14:07 UTC, WBDiamond commented on app/views/partials/widget.hbs
> +<div class="widget">
fe5e370

2018-03-13 14:33 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-13 14:36 UTC, WBDiamond commented
@noveogroup-amorgunov все пункты, кроме 5-го (стили), отрефакторил. Как сделать стили интереснее - не очень знаю. Это разве не работа дизайнеров?)))0)00

2018-03-13 15:17 UTC, WBDiamond commented
И, наверное, в следующий раз буду не напрямую с мастером все время работать

2018-03-14 08:29 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-14 08:47 UTC, noveogroup-amorgunov requested changes
Ну тут нужно проявить себя со всех сторон, в том числе красиво сверстать странички, несмотря что дизайн в задании никакущий) Но ладно, на счет дизайна отстаю :)

Давай подправим по мелочи еще, и я закрываю ПР. Сейчас все выглядит намного лучше, за использование более строго eslint-конфига 👍 

И все же нужно разобраться с обработкой ошибок, если я перехожу по http://localhost:8080/?query=Mos2cow то мне выводится странное сообщение: Not Found. Redirecting to error

2018-03-14 08:47 UTC, noveogroup-amorgunov commented on .eslintrc
> +//    "extends": "hrundel/node",
можно удалить его и забыть ))

2018-03-14 08:47 UTC, noveogroup-amorgunov commented on .eslintrc
> +    "extends": "airbnb",
У airbnb есть конфиг для ноды, сейчас править не нужно, на следующий раз

2018-03-14 08:47 UTC, noveogroup-amorgunov commented on .idea/encodings.xml
> +<?xml version="1.0" encoding="UTF-8"?>
еще нужно чтобы папка из git-a удалилась `git rm .idea`

2018-03-14 08:47 UTC, noveogroup-amorgunov commented on README.md
> +```
👍

2018-03-14 08:47 UTC, noveogroup-amorgunov commented on app/controllers/main.js
> +      ...res.locals, widget, categories, ...{ title: 'Погода' },
Если много параметров в объекте, то лучше не инлайнить в одну строчку
```js
{
   ...res.locals,
   widget,
   categories,
   title: 'Погода'
}
```

2018-03-14 08:47 UTC, noveogroup-amorgunov commented on app/controllers/news.js
> +      ...res.locals, widget, articles, ...{ title: 'Новости' },
как и в предыдущем контроллере не инлайнить параметры

2018-03-14 08:47 UTC, noveogroup-amorgunov commented on app/controllers/news.js
> +    Widget.get(req.query.query),
Можно не править, но будет лучше если использовать деструктизацию (не нужно везде повторять req.query):

```js
const { query, coutry, category } = req.query;
```

2018-03-14 08:47 UTC, noveogroup-amorgunov commented on app/middlewares/handle-errors.js
> +  res.sendStatus(500);
👍

2018-03-14 08:47 UTC, noveogroup-amorgunov commented on app/models/article.js
> +const { apiKey } = config;
А почему не 
`const { apiBasePath, apiKey } = require('../../config/localhost');`

2018-03-14 08:47 UTC, noveogroup-amorgunov commented on app/models/category.js
> +const categories = {
Давай все же вынесем в конфиг

2018-03-14 08:47 UTC, noveogroup-amorgunov commented on app/models/widget.js
> +    }
`static get (cityName = config.defaultCity)`
И условие удалить

2018-03-14 08:47 UTC, noveogroup-amorgunov commented on app/models/widget.js
> +const apiBasePath = `${config.weatherApiBasePath}api/location/`;
Я думаю тоже стоит вынести в конфиг, если url-ы все изменятся, не придется искать в коде ссылки кроме  конфига

2018-03-14 08:47 UTC, noveogroup-amorgunov commented on app/public/wind.svg
> +<?xml version="1.0" encoding="iso-8859-1"?>
Эту svg забыл минимизировать?

2018-03-14 08:47 UTC, noveogroup-amorgunov commented on config/localhost.js
> +  defaultCity: 'Moscow',
нужно префиксы добавить для apikey и defaultCity чтобы было ясно где они будут использоваться:
weatherDefaultCity и newsApiKey.
Или сделать конфиг с модулями типа:

```js
module.exports = {
  server: {
    debug: true,
    port: 8080,
    staticBasePath
  },
  weather: {
    defaultCity: 'Moscow',
    url: ''
  },
  news: {
    apiKey: '',
    url: ''
  }
};
```

2018-03-14 08:47 UTC, noveogroup-amorgunov commented on package.json
> +    "eslint-plugin-react": "7.4.0",
можно поставить 3 пакета и все должно работать:
```
    "eslint": "4.5.0",
    "eslint-config-airbnb-base": "11.3.1",
    "eslint-plugin-import": "2.7.0",
```

2018-03-14 08:47 UTC, noveogroup-amorgunov commented on app/models/widget.js
> +    return axios.get(`${apiBasePath}search/`, { params: { query: cityName } })
в конфиг путь вынести

2018-03-14 08:47 UTC, noveogroup-amorgunov commented on app/middlewares/common-data.js
> +const config = require('../../config/localhost');
Смотри, суть использования конфига с переменными окружениями (localhost, production) в том, что в зависимости от окружения получать различные конфиги. В коде ты пишешь require('config'), библиотека смотрит на process.env.NODE_ENV и в зависимости от значения переменной подключает нужный конфиг. Сейчас у тебя есть два варианта:
1. Оставить один конфиг и вынести его просто в корневую директорию назвав config.js
2. Подключить модуль node-config и создать два конфиг-файла в папке конфиг для среды local и production.

2018-03-14 08:47 UTC, noveogroup-amorgunov commented on config/localhost.js
> +  port: 8080,
Ты писал что хрюндель приложение не запускает если порт выносить в переменную окружения, но так можно делать же дефолтные значения: например на реальных проектах делают вот так:

```js
// config.js
const config = {
 // ...
 port: process.env.PORT || 8000

2018-03-14 17:49 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-14 18:59 UTC, WBDiamond commented on config/localhost.js
> +  port: 8080,
Не, там дело было в самой библиотеке, она его почему-то крашит

2018-03-14 19:07 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-03-14 19:11 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-03-14 19:12 UTC, WBDiamond commented
Не знаю, на что жалуется хрюндель

2018-03-15 03:26 UTC, noveogroup-amorgunov commented
@WBDiamond сейчас все выглядит круто!

На счет тестов, чтобы они прошли, нужно чтобы успешно выполнялась команда npm test. Сейчас эта команда выдает ошибку, потому что ты зависимости удалил вручную из package.json, а в package-lock.json они остались. Как поправить:

1. Удалить package-json.lock (такого делать по хорошему нельзя, но чтобы все быстро исправить придется)
2. В .eslintrc
```diff
 {
-    "extends": "airbnb",
+    "extends": "airbnb-base",
```
3. В package.json
```diff
     "lint": "eslint .",
-    "test": "npm run lint && mocha tests/*.js"
+    "test": "npm run lint && mocha tests/*.js --exit"

   "devDependencies": {
-    "eslint": "4.9.0",
-    "eslint-config-hrundel": "^1.3.0",
-    "eslint-config-airbnb": "16.1.0",
-    "eslint-plugin-import": "2.7.0",
+    "eslint": "^4.5.0",
+    "eslint-config-airbnb-base": "^11.3.1",
+    "eslint-plugin-import": "^2.7.0",
     "mocha": "^5.0.3",
```
3. Выполнить `npm i`и следом `npm test` (если все завершится без ошибки, то пушить изменения) и написать сюда

2018-03-15 03:27 UTC, noveogroup-amorgunov approved these changes

2018-03-15 03:27 UTC, noveogroup-amorgunov commented on config.js
> +  },
👍

2018-03-15 05:41 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-03-15 05:43 UTC, WBDiamond commented
@noveogroup-amorgunov вроде все сделал, продолжает валиться

2018-03-15 05:53 UTC, noveogroup-amorgunov commented
@WBDiamond  Попробуй запушить пустой коммит, пока не понимаю почему не проходит

2018-03-15 06:00 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-03-15 06:02 UTC, WBDiamond commented
@noveogroup-amorgunov мне Игорь Савичев скидывал лог из консоли хрюнделя, когда у меня вылились тесты еще до твоего ревью. Тогда мы узнали, что там библиотека 'config' его ломала, может в этот раз тоже ему какие-то библиотеки не нравятся?

2018-03-15 06:34 UTC, noveogroup-amorgunov commented
@WBDiamond замени из конфига вот эту строчку port: process.env.PORT || 8080, на port: 8081
Либо хрюндель перебивает PORT из окружения, либо что-то крутится уже на 8080 порту

2018-03-15 06:36 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-15 06:42 UTC, WBDiamond commented
О, круто. Правда во второй задаче тоже не может пройти тесты хрюнделя)

2018-03-15 06:46 UTC, noveogroup-amorgunov commented
Ну все, поздравляю)

2018-03-15 06:46 UTC, closed without merging