Елаков Евгений
urfu-2017/webdev-task-1 pull request #23
Opened 2018-03-07 18:28 UTC by Behemothhh

2018-03-07 18:28 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-07 18:33 UTC, Behemothhh commented
верстку попозже сделаю

2018-03-11 19:28 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-12 10:33 UTC, Superilya requested changes

2018-03-12 10:33 UTC, Superilya commented on .vscode/launch.json
> +{
.vscode в .gitignore

2018-03-12 10:33 UTC, Superilya commented on controllers/index.js
> +    const query = Object.entries(req.query)
https://www.npmjs.com/package/query-string

```
queryString.stringify()
```

2018-03-12 10:33 UTC, Superilya commented on controllers/index.js
> +    const query = Object.entries(req.query)
во всех местах

2018-03-12 10:33 UTC, Superilya commented on controllers/news.js
> +module.exports = (country, category) => News.gettNews(country, category);
это не контроллер, контроллер должен вызываться из роутера

2018-03-12 10:33 UTC, Superilya commented on controllers/index.js
> +        weatherController(req.query),
это контроллер и зачем делать weatherController не понятно, модели достаточно

2018-03-12 10:33 UTC, Superilya commented on models/api.js
> +module.exports.getWeather = woeid => {
даже то как ты назвал функцию `getWeather ` показывает что api это не модель, у тебя есть модель Weather ну и сделай в ней метод `get`. Хочется вынести логику для запросов, делай базовую модель наследуйся от неё, и пусть модель Weather использует базовый метод для запроса

2018-03-12 10:33 UTC, Superilya commented on models/news.js
> +    static gettNews(country, category) {
опечатка

2018-03-12 10:33 UTC, Superilya commented on public/news.svg
> +<?xml version="1.0" encoding="iso-8859-1"?>
хороший тон, прогнать svg через svgo, лучше делать это при сборке проекта. Кароч тебе надо знать что svg надо обрабатывать перед отправкой клиенту, если нет автоматизации для . этого придётся сделать это руками

2018-03-12 10:41 UTC, Superilya commented
Не понял зачем ты делал префикс render для функций которые используешь в роутере. Это и есть контроллеры. Контроллер должен использовать модель и в общем виде выглядеть вот так
```
const controller = async (req, res, next) => {
    const weather = new WeatherModel(req);
    const weatherData = await weather.get();

    await res.render('category', weatherData);
}
```

Цитата
```
Обратите внимание, что информация о погоде используется сразу на двух страницах, и было бы очень круто, если бы этот код был написан 1 раз.
```
тонкий намёк на базовую модель, методы которой могут переиспользовать WeatherModel и NewsModel

2018-03-12 14:07 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-14 15:40 UTC, Superilya commented on controllers/baseController.js
> +    weatherController
я надеюсь это опечатка, инстанс модели это не контроллер

2018-03-14 15:40 UTC, Superilya commented
Есть проблемы с наименованием, если класс называется Weather, то зачем называть метод getWeather? `Weather.getWeather` очень странно. С контроллерами тоже самое, если файл лежит в каталоге controllers, зачем давать ему постфикс controllers? И используй в будущем больше async/await, вообще везде где можно, когда асинхронщина будет сложная, будет понятнее. Это не критично, главное по структуре всё правильно.

2018-03-14 15:40 UTC, closed without merging