Яркеев Станислав
urfu-2017/webdev-task-1 pull request #26
Opened 2018-03-07 18:38 UTC by Admirallll

2018-03-07 18:39 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-03-07 18:41 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-07 19:23 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-11 17:39 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-13 07:49 UTC, VasiliiKuznecov requested changes

2018-03-13 07:49 UTC, VasiliiKuznecov commented on index.js
> +const getWeather = require('./weather').getWeather;
кажется, эти файлы должны быть в папке models, раз они выполняют роль моделей

2018-03-13 07:49 UTC, VasiliiKuznecov commented on index.js
> +function indexController(req, res) {
контроллеры лучше тоже выносить в отдельную папку и разбивать по файлам, ибо их может быть много

2018-03-13 07:49 UTC, VasiliiKuznecov commented on index.js
> +app.use((req, res, next) => {
это middleware, вынеси в отдельную папку и файл. Что-нибудь вроде `middlewares/weather.js`.
Так лучше делать, потому что обычно миддлвар бывает много и они могут использоваться в разных местах

2018-03-13 07:49 UTC, VasiliiKuznecov commented on index.js
> +    getWeather(req.query.query, req.query.lat, req.query.lon)
может, прокидывать тогда просто req.query? чтобы не нужно было запоминать порядок + req.query.query может не быть и непонятно, зачем передавать первый пустой аргумент

2018-03-13 07:49 UTC, VasiliiKuznecov commented on index.js
> +        .then((response) => {
скобки не нужны

2018-03-13 07:49 UTC, VasiliiKuznecov commented on index.js
> +    let weather = res.locals.weather;
почему let?

2018-03-13 07:49 UTC, VasiliiKuznecov commented on index.js
> +            let news = response.body.articles.filter(
почему let?

2018-03-13 07:49 UTC, VasiliiKuznecov commented on index.js
> +                (article) => article.description !== null && article.description.length !== 0
скобки не нужны

2018-03-13 07:49 UTC, VasiliiKuznecov commented on index.js
> +                (article) => article.description !== null && article.description.length !== 0
`article.description !== null && article.description.length !== 0` кажется можно заменить на `Boolean(article.description)` или даже просто `article.description`

2018-03-13 07:49 UTC, VasiliiKuznecov commented on news.js
> +    let fullUrl = `${url}category=${category}&country=${country}&apiKey=${apiKey}`;
сделал обработку country, но не прокидываешь сюда второй аргумент никогда

2018-03-13 07:49 UTC, VasiliiKuznecov commented on news.js
> +    let fullUrl = `${url}category=${category}&country=${country}&apiKey=${apiKey}`;
может, `?` перенести сюда из файла json? как-то он здесь логичнее смотрится, чем в конфиге в урле почему-то стоит `?`

2018-03-13 07:49 UTC, VasiliiKuznecov commented on news.js
> +    return got(fullUrl, { json: true }, response => response);
кажется, третий аргумент не нужен

2018-03-13 07:49 UTC, VasiliiKuznecov commented on package.json
> +    "request": "^2.83.0"
зачем нужен request?

2018-03-13 07:49 UTC, VasiliiKuznecov commented on public/styles.css
> +.news-title {
пустой селектор?

2018-03-13 07:49 UTC, VasiliiKuznecov commented on public/styles.css
> +.category-icon {
приведи все названия классов к методологии БЭМ
например, иконка здесь это элемент блока `category`
поэтому класс должен быть `category__icon`

2018-03-13 07:49 UTC, VasiliiKuznecov commented on views/index.handlebars
> +        <i class="fas fa-lg fa-{{icon}} category-icon"></i><a class="category-name" href="news/{{name}}">{{text}}</a><br>
сделай пожалуйста без br

2018-03-13 07:49 UTC, VasiliiKuznecov commented on views/index.handlebars
> +    <div class="category">
что-то отступы неправильные

2018-03-13 07:49 UTC, VasiliiKuznecov commented on views/index.handlebars
> +    <div class="categories">
может, ul / li?

2018-03-13 07:49 UTC, VasiliiKuznecov commented on views/layouts/main.handlebars
> +    <div class="header">
тэг header

2018-03-13 07:49 UTC, VasiliiKuznecov commented on views/layouts/main.handlebars
> +            <div class="">
что за div без класса?

2018-03-13 07:49 UTC, VasiliiKuznecov commented on views/layouts/main.handlebars
> +                        <div class="weather-small">
article?

2018-03-13 07:49 UTC, VasiliiKuznecov commented on views/layouts/main.handlebars
> +                    <div><span class="temp-letter">t </span>{{weather.current.temp}}&deg;С</div>
у температуры обычно пишут +, если она > 0

2018-03-13 07:49 UTC, VasiliiKuznecov commented on views/layouts/main.handlebars
> +    <div class="footer">
тэг footer

2018-03-13 07:49 UTC, VasiliiKuznecov commented on views/news.handlebars
> +<div class="news">
тэг article

2018-03-13 07:49 UTC, VasiliiKuznecov commented on views/news.handlebars
> +</div>
новости бывают с картинкой, надо добавлять в таком случае

2018-03-13 07:49 UTC, VasiliiKuznecov commented on weather.js
> +    const weatherUrl = `https://www.metaweather.com/api/location/${woeid}/`;
может, по аналогии с новостями вынести тогда в json?

2018-03-13 07:49 UTC, VasiliiKuznecov commented on views/news.handlebars
> +        <div class="news-date">{{publishedAt}}</div>
время у новости лучше бы было в более человекочитаемом виде

2018-03-13 07:49 UTC, VasiliiKuznecov commented on weather.js
> +function prettifyDate(source) {
обычно пишут 14 апреля, а не 14 Апрель

2018-03-13 07:49 UTC, VasiliiKuznecov commented on weather.js
> +function prettifyDate(source) {
в форматировании дат может помочь библиотека `moment`

2018-03-13 07:49 UTC, VasiliiKuznecov commented on weather.js
> +        .catch(() => defaultWoeid);
зачем нам делать запрос, чтобы понять, что ни query, ни latlon нет?

2018-03-13 18:28 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-15 11:25 UTC, VasiliiKuznecov approved these changes

2018-03-15 11:25 UTC, VasiliiKuznecov commented on controllers/indexController.js
> +'use strict';
раз файл уже в папке controllers, можно не уточнять это еще и в названии
просто controllers/index.js , controllers/news.js

2018-03-15 11:25 UTC, VasiliiKuznecov commented on views/news.handlebars
> +        <img class="news-image" src="{{urlToImage}}">
но картинки может и не быть, по-хорошему, надо это проверять

2018-03-15 11:25 UTC, VasiliiKuznecov commented on views/news.handlebars
> +        <img class="news__image" src="{{urlToImage}}">
по-хорошему, urlToImage может не быть и в таком случае img не нужно выводить вообще

2018-03-15 11:25 UTC, closed without merging