back-end
urfu-2017/webdev-task-1 pull request #27
Opened 2018-03-07 18:53 UTC by HazipovVF

2018-03-07 18:53 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-03-07 19:03 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-03-07 19:05 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-03-07 19:17 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-07 19:18 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-07 19:19 UTC, HazipovVF commented
всего-то нужно было подключить зависимости эх

2018-03-07 22:24 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-25 12:33 UTC, savichev-igor requested changes
Из MVC:

View - сделано хорошо
M и C - страдают пока

Ещё я бы прикрутил какой-нибудь кэш, а то `API` отвечают крайне долго

Местами ещё форматирование страдает

2018-03-25 12:33 UTC, Savichev-Igor commented on controllers/all.js
> +const newsapi = new NewsAPI('574326253ac74f489b5f5015089a3c66');
Лучше это всё выносить в `ENV` переменные и использовать какой-нибудь модуль, например `dotenv`

2018-03-25 12:33 UTC, Savichev-Igor commented on controllers/all.js
> +    res.locals.categories = Category.findAll();
А что ты делаешь с данными, которые пишешь в `res`?

2018-03-25 12:33 UTC, Savichev-Igor commented on controllers/all.js
> +    let data = res.locals;
Зачем выносить в переменную, если это только в одном месте используется?

2018-03-25 12:33 UTC, Savichev-Igor commented on controllers/all.js
> +    var countries = ['ru', 'au', 'at', 'be', 'br', 'ca', 'ua', 'gb', 'us'];
Вынести в константы

2018-03-25 12:33 UTC, Savichev-Igor commented on controllers/all.js
> +    if (name === 'everything') {
Что за значение параметра такое?

2018-03-25 12:33 UTC, Savichev-Igor commented on controllers/all.js
> +        res.locals.news = response.articles;
Аналогичные вопросы, как выше

2018-03-25 12:33 UTC, Savichev-Igor commented on controllers/errors.js
> +exports.error404 = (req, res) => res.sendStatus(404);
👍

2018-03-25 12:33 UTC, Savichev-Igor commented on controllers/getweather.js
> +const link = 'https://www.metaweather.com/api/location/';
Это всё нужно выносить в какой-нибудь `config.json` и собирать ссылки с помощью встроенного модуля `url`, где ты указываешь протокол, хост, путь и прочее

2018-03-25 12:33 UTC, Savichev-Igor commented on controllers/getweather.js
> +    var XMLHttpRequest = require('xmlhttprequest').XMLHttpRequest;
Почему не используешь какой-нибудь `got` или `request`? Выглядит он сильно проще

2018-03-25 12:33 UTC, Savichev-Igor commented on controllers/getweather.js
> +        xhr.open('GET', link + 'search/?query=' + city, false);
Зачем складывать строки, если есть интерполяция?

И опять же, все ссылки нужно собирать модулем `url`

2018-03-25 12:33 UTC, Savichev-Igor commented on controllers/all.js
> +    var country = req.query;
Почему `var`ы?

2018-03-25 12:33 UTC, Savichev-Igor commented on index.js
> +
Слишком много пустых строк, одной достаточно для логического разделения

2018-03-25 12:33 UTC, Savichev-Igor commented on index.js
> +    new Category(cat).save();
Категории совсем ни к чему выносить в модели

Достаточно моделей: погода на сегодняшний день и новостной пост

2018-03-25 12:33 UTC, Savichev-Igor commented on index.js
> +    res.locals.weather = getWeather(req.query);
Если ты используешь `getWeather` как мидлвару, то создай папку `middlewares` и положи все мидлвары туда

2018-03-25 12:33 UTC, Savichev-Igor commented on mocks/categories.json
> +  ]
Форматирование странное

2018-03-25 12:33 UTC, Savichev-Igor commented on models/category.js
> +class Note {
Модель ни к чему

2018-03-25 12:33 UTC, Savichev-Igor commented on models/weather.js
> +        weatherArr.forEach(elem => {
В модели не должно быть никакой логики

Хороший пример моделей можно увидеть у Алексея Дубровина

2018-03-25 12:33 UTC, Savichev-Igor commented on models/weather.js
> +function getRusTime(time) {
Мне кажется, что всё можно сделать с помощью встроенных средств в `NodeJS`

2018-03-25 12:33 UTC, Savichev-Igor commented on public/index.css
> +}
Пустая строка?

2018-03-25 12:33 UTC, Savichev-Igor commented on public/index.css
> +.news-list{
Давай прикрутим `stylelint`, как было в задачах на вёрстку, в прошлом семестре

2018-03-25 12:33 UTC, Savichev-Igor commented on public/index.css
> +.news-list-summury__title {
А ещё давай прикрутим какой-нибудь сборщик и пре/пост процессоры

2018-03-25 12:33 UTC, Savichev-Igor commented on routes.js
> +    app.get('/news/:name', news);
Неужели их нельзя никак слить в один, с верхним?

2018-03-25 12:33 UTC, Savichev-Igor commented on views/test.html
> +    <meta charset="{{ meta.charset }}">
Что за `test.html`?

2018-03-25 12:33 UTC, Savichev-Igor commented on controllers/all.js
> +        language: 'ru',
Почему язык всегда русский?

2018-03-25 12:34 UTC, Savichev-Igor commented on views/news.hbs
> +    <meta charset="{{ meta.charset }}">
Эта часть вёрстки уже явно повторяется, используй `layout`

2018-03-27 06:53 UTC, HazipovVF commented on controllers/all.js
> +const newsapi = new NewsAPI('574326253ac74f489b5f5015089a3c66');
Согласен, руководствовался этим
Но здесь делаем исключение, ибо все эти API общедоступные и в принципе ничего страшного в этом нет

2018-03-27 06:57 UTC, HazipovVF commented on controllers/all.js
> +    res.locals.categories = Category.findAll();
Загружаю в index.hbs
        {{#each categories }}
        <div class="news-categories">
            <a class="news-categories__category" href={{url}}>{{name}}</a>
        </div>
        {{/each}}

2018-03-27 07:00 UTC, Savichev-Igor commented on controllers/all.js
> +const newsapi = new NewsAPI('574326253ac74f489b5f5015089a3c66');
Ты неправильно понял.

Имелось ввиду, что ничего страшного в том, что мы запушим тот `.env` файл, который ты создашь, используя модуль `dotenv`, а не вот так открыто в коде токены хранить

2018-03-27 07:01 UTC, Savichev-Igor commented on controllers/all.js
> +    res.locals.categories = Category.findAll();
Прокидывай как нормальный контекст, а не через `res`

2018-03-27 07:04 UTC, HazipovVF commented on controllers/all.js
> +    if (name === 'everything') {
У меня есть ряд категорий 
Одна  из них общее 
"name": "Общее",
"url": "/news/everything"
Чтобы не прописывать отдельный запрос newsapi.v2.everything ...
решил обнулить категорию, чтобы вывести все

2018-03-27 07:38 UTC, HazipovVF commented on controllers/getweather.js
> +    var XMLHttpRequest = require('xmlhttprequest').XMLHttpRequest;
request уже использовал в том семестре
тут решил попробовать xmlhttprequest
в 3 лабе окончательно перешел на fetch

2018-03-27 09:36 UTC, HazipovVF commented on controllers/all.js
> +    let data = res.locals;
+

2018-03-27 09:36 UTC, HazipovVF commented on controllers/all.js
> +    var countries = ['ru', 'au', 'at', 'be', 'br', 'ca', 'ua', 'gb', 'us'];
+

2018-03-27 09:37 UTC, HazipovVF commented on controllers/all.js
> +        res.locals.news = response.articles;
+

2018-03-27 09:37 UTC, HazipovVF commented on controllers/all.js
> +    var country = req.query;
плохая привычка

2018-03-27 09:38 UTC, HazipovVF commented on index.js
> +
+

2018-03-27 09:38 UTC, HazipovVF commented on index.js
> +    res.locals.weather = getWeather(req.query);
+

2018-03-27 09:39 UTC, HazipovVF commented on mocks/categories.json
> +  ]
+

2018-03-27 09:39 UTC, HazipovVF commented on public/index.css
> +.news-list{
+

2018-03-27 09:40 UTC, HazipovVF commented on public/index.css
> +}
+

2018-03-27 09:42 UTC, HazipovVF commented on public/index.css
> +.news-list-summury__title {
Сейчас уже будет странно писать препроцессор, при наличии готового css
В 4 задаче использую

2018-03-27 10:04 UTC, HazipovVF commented on routes.js
> +    app.get('/news/:name', news);
упростил

2018-03-27 10:07 UTC, HazipovVF commented on views/test.html
> +    <meta charset="{{ meta.charset }}">
Проверял html
удалил

2018-03-27 10:09 UTC, HazipovVF commented on views/news.hbs
> +    <meta charset="{{ meta.charset }}">
+

2018-03-27 10:23 UTC, HazipovVF commented on controllers/all.js
> +const newsapi = new NewsAPI('574326253ac74f489b5f5015089a3c66');
+

2018-03-27 17:13 UTC, HazipovVF commented on controllers/getweather.js
> +        xhr.open('GET', link + 'search/?query=' + city, false);
link + 'search/?query=' + city
но ведь url.resolve не соберет такую ссылку

2018-03-27 17:14 UTC, HazipovVF commented on controllers/all.js
> +        language: 'ru',
Не хотел смотреть новости на других языках

2018-03-27 17:17 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-27 17:43 UTC, HazipovVF commented on models/weather.js
> +function getRusTime(time) {
var timeObject = new Date().toLocaleDateString('ru', {
        day: 'numeric',
        month: 'long'

      });
    console.log(timeObject);
В браузере дает то что надо
В node.js нет

2018-03-28 05:25 UTC, savichev-igor requested changes
Правильных моделей я так и не увидел

Замечания с прошлой проверки тоже не все исправлены

Да и вообще задание выполнено не полностью: `country` не меняет новости

Если ты так пренебрежительно относишься к требованиям задания, то больше чем `half-points` я тебе предлагать не буду

2018-03-28 05:25 UTC, Savichev-Igor commented on middlewares/getLocalData.js
> +    `https://www.metaweather.com/static/img/weather/${data.weatherArr[0].weather_state_abbr}.svg`;
Такое тоже лучше выносить в `конфиг.js` какой-нибудь

2018-03-28 05:25 UTC, Savichev-Igor commented on middlewares/getLocalData.js
> +    var months = ['Январь', 'Февраль', 'Марта', 'Апрель', 'Май', 'Июнь', 'Июль', 'Август',
В константы

2018-03-28 05:25 UTC, Savichev-Igor commented on middlewares/getLocalData.js
> +    return timeObject.getDate() + ' ' + months[timeObject.getMonth()];
`${timeObject.getDate()} ${months[timeObject.getMonth()]}`

2018-03-28 05:25 UTC, Savichev-Igor commented on middlewares/getweather.js
>      var city = query.query;
Опять `var`'ы

2018-03-28 05:25 UTC, Savichev-Igor commented on middlewares/getweather.js
> +var url = require('url');
За тебя кто-то пишет код или ты его откуда-то копируешь? Тут `var`, там `const`

2018-03-28 05:25 UTC, Savichev-Igor commented on middlewares/getweather.js
> +
???

2018-03-28 05:25 UTC, Savichev-Igor commented on middlewares/getweather.js
> +    xhr.open('GET', `${link}44418/`, false);
А объясни, пожалуйста, почему именно такое значение?

`44418`?

2018-03-28 05:25 UTC, Savichev-Igor commented on models/weather.js
> +        // нелогичный класс
Почему?

2018-03-28 05:25 UTC, Savichev-Igor commented on models/weather.js
> +        this.weatherArr = data.consolidated_weather;
Почему у тебя здесь массив?

Почему ты не посмотрел у Алексея Дубровина модели?

2018-03-28 05:25 UTC, Savichev-Igor commented on package.json
> +    "url": "^0.11.0",
Есть встроенный модуль в `NodeJS`

2018-03-28 05:25 UTC, Savichev-Igor commented on views/partials/layout.hbs
> +<!DOCTYPE html>
Это не похоже на `layout`, тут `body` нет

Можешь опять же у Алексея Дубровина посмотреть как их нормально делать

2018-03-28 05:25 UTC, Savichev-Igor commented on views/partials/weather.hbs
> +</header
?

2018-03-28 05:29 UTC, Savichev-Igor commented on controllers/getweather.js
> +        xhr.open('GET', link + 'search/?query=' + city, false);
```
const url = format({
        protocol: defaultValues.PROTOCOL,
        host,
        pathname,
        query: params
});
```

2018-03-28 11:24 UTC, HazipovVF commented on middlewares/getweather.js
> +var url = require('url');
https://www.npmjs.com/package/url
строку скопировал

2018-03-29 04:08 UTC, HazipovVF commented on middlewares/getweather.js
> +    xhr.open('GET', `${link}44418/`, false);
Базовый id лондона

2018-03-29 04:12 UTC, HazipovVF commented on models/weather.js
> +        this.weatherArr = data.consolidated_weather;
Избавлялся от логики в модели
Получалось так что после создания модели, перед тем как ее вывести нужно разобрать массив
сейчас переделал

2018-03-29 05:00 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-29 05:03 UTC, HazipovVF commented
Поправил ошибку со страной и языком
http://localhost:8080/news/health?country=be
Исправил модель
Убрал вары
Добавил layout

2018-03-29 05:05 UTC, HazipovVF commented
weather.hbs ведет себя странно в index не вставляется в news вставляется, пришлось вставить в index
И это только в тестах

2018-03-29 08:07 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-30 16:52 UTC, savichev-igor requested changes
Зачем пустые файлы типа `error.js`?

`middleWeatherCorrrecter` тоже странное имя для папки, можно было просто сделать `middlewares`

Получение погоды в мидлвару так и не вынес, получаешь на обеих страницах её заново

Модели новости я так и не увидел, хотя даже сказал у кого посмотреть хорошие модели

2018-03-30 16:52 UTC, Savichev-Igor commented on views/news.hbs
> +
Почему так много лишних строк?

2018-03-30 16:52 UTC, Savichev-Igor commented on views/layout.hbs
> +</html>
Пустой строки нет

2018-03-30 16:52 UTC, Savichev-Igor commented on views/index.hbs
> +
?

2018-03-30 16:52 UTC, Savichev-Igor commented on views/index.hbs
> +
?

2018-03-30 16:52 UTC, Savichev-Igor commented on views/index.hbs
> +        <table class = "table">
` = ` это что?

2018-03-30 16:52 UTC, Savichev-Igor commented on views/partials/weather.hbs
> +</header>
Пустая строка

2018-03-30 16:52 UTC, Savichev-Igor commented on views/partials/weather.hbs
> +                <td class="table__col">{{ wind }} м/c</td>
Можно было отступ, вложенность же

2018-03-30 16:52 UTC, Savichev-Igor commented on views/partials/newsLi.hbs
> +    <main>
Зачем отступ?

2018-03-30 16:52 UTC, Savichev-Igor commented on views/partials/newsLi.hbs
> +    </main>
Пустая строка

2018-03-30 16:52 UTC, Savichev-Igor commented on views/partials/newsCat.hbs
> +        <a class="news-categories__category" href="/news/business">Бизнес</a>
`href`'ы нужно подсасывать из конфига

2018-03-30 16:52 UTC, Savichev-Igor commented on views/partials/newsCat.hbs
> +</main>
Blank line

2018-03-30 16:52 UTC, Savichev-Igor commented on models/weather.js
> +const months = ['Января', 'Февраля', 'Марта', 'Апреля', 'Мая', 'Июня', 'Июля', 'Августа',
Можно было каждый элемент с новой строки, так хотя бы читалось проще

2018-03-30 16:52 UTC, Savichev-Igor commented on middleWeatherCorrecter/getweather.js
> +const BASE_LONDON_ID = 44418;
так константы уже не имеют, то что переменная константа гарантирует `const`

2018-03-30 16:52 UTC, Savichev-Igor commented on middleWeatherCorrecter/getweather.js
> +    if (!cache.get(city)) {
Почему заполняешь кэш не в том же месте, где пытаешься получить?

2018-03-30 16:52 UTC, Savichev-Igor commented on middleWeatherCorrecter/getweather.js
> +    data.consolidated_weather.forEach(element => {
`.map`

2018-03-30 18:42 UTC, HazipovVF commented on middleWeatherCorrecter/getweather.js
> +const BASE_LONDON_ID = 44418;
вот это не понял немного

2018-03-30 18:57 UTC, HazipovVF commented on middleWeatherCorrecter/getweather.js
> +    if (!cache.get(city)) {
С кэшем работаю первый раз, поэтому решил туда добавлять уже правильные данные, а не огромную строку ответа api

2018-03-30 19:32 UTC, HazipovVF commented on views/partials/newsLi.hbs
> +    <main>
Не заметил при переносе

2018-03-30 20:02 UTC, HazipovVF commented
на счет моделей
У Алексея я посмотрел модели ,но делал модель погоды так как там были ошибки
Про модель новости мы не говорили
сейчас сделаю

2018-03-30 20:03 UTC, HazipovVF commented on views/news.hbs
> +
Пишу ночью 
Такие вещи порой замыливаются

2018-03-30 20:52 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-03-30 20:56 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-03-30 21:25 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-03-30 21:30 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-03-30 21:47 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-03-30 21:50 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-04-01 12:34 UTC, savichev-igor approved these changes
Урлы всё равно плохо собираешь

2018-04-01 12:34 UTC, Savichev-Igor commented on views/partials/newsCat.hbs
> +
Лишняя

2018-04-01 12:35 UTC, closed without merging