Нуриев Михаил
urfu-2017/webdev-task-1 pull request #29
Opened 2018-03-07 18:55 UTC by NurievMikhail

2018-03-07 18:56 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-10 10:03 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-13 09:25 UTC, noveogroup-amorgunov requested changes
1. Изменить файл readme. Указать, что нужно сделать для запуска приложения (например выполнить npm install и npm start потому что сейчас команд нет, при запуске index.js в консоль ничего не выводится, непонятно как запустить приложение) и потом по такому то url будет доступно приложение), а задание можно вынести просто ссылкой
2. Если останется время, можно посмотреть на eslint конфиг от airbnb (https://github.com/airbnb/javascript, https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb) вместо хрюндель-конфига, так как он сам будет отлавливать множество стилистических ошибок (например использования const вместо let, если переменная не изменяется, сокращенная запись объекта, лишние пробелы итд)
3. Переделать стили в соответствии с методологией бэм. И нужно немного улучшить визуальное оформление, пока выглядит плохо

2018-03-13 09:25 UTC, noveogroup-amorgunov commented on controllers/category.js
> +const url = require('url');
Хорошая практика подключать сначала внешние модули, потом свои

2018-03-13 09:25 UTC, noveogroup-amorgunov commented on controllers/category.js
> +const NewsArticle = require('../models/news-article');
Почему не просто News? :)

2018-03-13 09:25 UTC, noveogroup-amorgunov commented on controllers/category.js
> +    let query = url.parse(req.url, true).query;
Если переменная дальше не изменяется, то вместо let нужно использовать const

2018-03-13 09:25 UTC, noveogroup-amorgunov commented on controllers/category.js
> +    let query = url.parse(req.url, true).query;
query можно получить как req.query

2018-03-13 09:25 UTC, noveogroup-amorgunov commented on controllers/category.js
> +    const weathers = await Weather.findAll(query.query, query.lat, query.lon);
в js есть прием по передаче параметров в метод в виде одного объекта, если их больше одного. Сразу ясно какой параметр за что отвечает и порядок не важен: `NewsArticle. findAll({ country: query.country, category: req.params.category })`

2018-03-13 09:25 UTC, noveogroup-amorgunov commented on controllers/category.js
> +    let resultData = Object.assign(data, res.locals);
let -> const

2018-03-13 09:25 UTC, noveogroup-amorgunov commented on controllers/category.js
> +'use strict';
все же эта страница на сайте показывает "**список новостей** по категории", а не данные по категории, поэтому и назвать его лучше news.js

2018-03-13 09:25 UTC, noveogroup-amorgunov commented on controllers/index.js
> +    res.render('index', resultData);
поправить все замечания из другого контроллера (let -> const, получение query)

2018-03-13 09:25 UTC, noveogroup-amorgunov commented on index.js
> +app.use((req, res, next) => {
лучше вынести этот мидделавар в отдельный файл `middlewares/setInitialData.js` В нем же можно подгружать погоду (чтобы это не делать в каждом контроллере отдельно)

2018-03-13 09:25 UTC, noveogroup-amorgunov commented on index.js
> +    app.listen(8080);
Порт нужно вынести в конфиг

2018-03-13 09:25 UTC, noveogroup-amorgunov commented on index.js
> +    app.listen(8080);
Нужно вывести сообщение, что сервер запущен на таком то порту

2018-03-13 09:25 UTC, noveogroup-amorgunov commented on index.js
> +hbs.registerPartials(partialsDir, () => {
Оставь комментарий, зачем запуск приложения оборачивать в hbs.registerPartials

2018-03-13 09:25 UTC, noveogroup-amorgunov commented on index.js
> +app.use((req, res, next) => {
Нужно создать папочку middlewares и туда добавить `handleErrors.js` мидлевару, которая будет обрабатывать ошибки (пример есть в приложении с заметками, там правда этот мидлевар заинлайнен в app.js)

В этой мидлеваре вызывать res.render('error'), где error - это шаблон со страницей-ошибкой (например просто выводить "что-то пошло не так, извиняйте, перейти на главную".

2018-03-13 09:25 UTC, noveogroup-amorgunov commented on models/weather.js
> +        let woeid = (await weatherSearchHelper(query))[0].woeid;
Если я в query введу не город (например набор цифр), то страница не загрузится, а в консоле выпадет ошибка:
```
(node:81318) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:81318) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'woeid' of undefined
```

Поэтому нужно проверять, что `cityList[0]` не равен `undefined`. И если он равен undefined - то можно выбрасывать ошибку и обрабатывать ее в middleware по обработке ошибок.

2018-03-13 09:25 UTC, noveogroup-amorgunov commented on models/news-article.js
> +const request = require('request');
лучше использовать модуль axios - один из топовых модулей по работе с запросами (или request-promise)

2018-03-13 09:25 UTC, noveogroup-amorgunov commented on models/news-article.js
> +const URL = 'https://newsapi.org/v2/top-headlines';
вынести в конфиг

2018-03-13 09:25 UTC, noveogroup-amorgunov commented on models/news-article.js
> +function newsHelper(query) {
Название метода не верное (Хелпер новостей), а на самом деле метод отправляет запрос на получение данных, лучше назвать fecth/load.

2018-03-13 09:25 UTC, noveogroup-amorgunov commented on models/news-article.js
> +function newsHelper(query) {
если использовать аксиос то не нужно оборачивать в промис и не нужно query параметры преобразовывать в строку, будет достаточно написать:

```js
axios.get(newsApiUrl, { params: { apiKey, category, country } })
```
Аксиос сам преобразует объект в query-строку.

2018-03-13 09:25 UTC, noveogroup-amorgunov commented on models/news-article.js
> +        let storage = [];
let -> const

2018-03-13 09:25 UTC, noveogroup-amorgunov commented on models/news-article.js
> +        const query = querystring.stringify({ 'apiKey': '312ce60d1fca4335896fee931ab1a01b',
API_KEY перенести в конфиг, а еще лучше в переменные среды ( можно почитать о библиотеки [dotenv](https://github.com/motdotla/dotenv)). Если кратко, то у тебя есть файл `.env` в котором хранятся все секретные ключи и который не нужно коммитить, например:

```
NEWSAPI_KEY= d333fab019c840009dd5a977f05c7280
```
И потом в коде в конфиге получить его:  

```
const config = {
  // ...
  newsApiKey: process.env.NEWSAPI_KEY;`
};
```
и где нужно читать уже из конфига.

2018-03-13 09:25 UTC, noveogroup-amorgunov commented on models/news-article.js
> +        return Promise.resolve(storage);
не нужно в resolve оборачивать, если ты функцию объявляешь как async, то js сам обернет ее в промис

2018-03-13 09:25 UTC, noveogroup-amorgunov commented on models/news-article.js
> +        for (const newsArticle of news) {
можно сделать без for-of и без переменной storage (меньше кода, или переименовать storage в переменную с соответствующим названием):

```
return news.map(data => {
    // .....
    return new NewsArticle(..);
})
```

2018-03-13 09:25 UTC, noveogroup-amorgunov commented on models/weather.js
> +        return 'moscow';
можно в конфиг унести

2018-03-13 09:25 UTC, noveogroup-amorgunov commented on models/weather.js
> +    let resultUrl = URL + woeid + '/';
Все замечания нужно поправить из модели news и тут

2018-03-13 09:25 UTC, noveogroup-amorgunov commented on models/weather.js
> +        this.temp = temp;
предлагаю переименовать temp -> temperature (чтобы было ясно, что это точно температура, а никакая не временная переменная)

2018-03-13 09:25 UTC, noveogroup-amorgunov commented on models/news-article.js
> +    return createRequestPromise(options);
Сайт же на русском языке? Значит новости тоже нужно только на русском подгружать

2018-03-13 09:25 UTC, noveogroup-amorgunov commented on models/weather.js
> +            query = querystring.stringify({ 'lattlong': `${lat},${lon}` });
Я ввел в url /?lat=4 и у меня нода выкинула ошибку:

```
(node:98592) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:98592) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: weathers is not iterable
```
Как минимум нужно проверять что lat и lon существуют

2018-03-13 09:25 UTC, noveogroup-amorgunov commented on package.json
> -    "start": "node index.js",
Зачем удалил скрипт для запуска приложения и прогона тестов?

2018-03-13 09:25 UTC, noveogroup-amorgunov commented on package.json
> +    "config": "1.29.4",
Есть конфиг в зависимостях, а не используется

2018-03-13 09:25 UTC, noveogroup-amorgunov commented on public/c.svg
> +<!-- Generator: Adobe Illustrator 16.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
Давай все svg прогоним черех svgo

2018-03-13 09:25 UTC, noveogroup-amorgunov commented on public/category.css
> +.newsHeader
не по методологии бэм, нужно переделать

2018-03-13 09:25 UTC, noveogroup-amorgunov commented on public/category.css
> +	border-right: solid #9babff 1px;
пробелы лишнии

2018-03-13 09:25 UTC, noveogroup-amorgunov commented on public/category.css
> +	border-right: solid #9babff 1px;
опять

2018-03-13 09:25 UTC, noveogroup-amorgunov commented on public/index.css
> +.pageName
тоже не по бэму, в css не используется camelCase, правильно: page-name

2018-03-13 09:25 UTC, noveogroup-amorgunov commented on public/index.css
> +.categories__category
переименовать categories__item

2018-03-13 09:25 UTC, noveogroup-amorgunov commented on public/c.svg
> +<!-- Generator: Adobe Illustrator 16.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
И все иконки для погоды перенесем в подкаталог weather-icons

2018-03-13 09:25 UTC, noveogroup-amorgunov commented on public/weather.css
> +.weatherState__image
в этом файлики тоже селекторы не по бэм-у

2018-03-13 09:25 UTC, noveogroup-amorgunov commented on views/category.hbs
> +</head>
У всех шаблонов один и тот же layout - нужно вынести в один файл

2018-03-13 09:25 UTC, noveogroup-amorgunov commented on views/category.hbs
> +<header>
отступ потерялся

2018-03-13 09:25 UTC, noveogroup-amorgunov commented on views/index.hbs
> +        <li><a class="categories__category" href="../business">Бизнес</a></li>
категории нужно вынести в конфиг, на сервере добавлять их в req.locals и здесь (в шаблоне) выводить через each

2018-03-13 09:25 UTC, noveogroup-amorgunov commented on views/partials/news.hbs
> +                    <img class="newsHeader__img" src="{{ urlToImage }}" alt="Картинка для новости">
такой alt бессмысленный, можно заменить значения на название новости

2018-03-13 09:25 UTC, noveogroup-amorgunov commented on views/partials/news.hbs
> +                <div class="newsFooter__date"> {{ publishedAt }}</div>
дату нужно форматировать

2018-03-13 09:25 UTC, noveogroup-amorgunov commented on views/partials/news.hbs
> +    <p>Новости не найдены :(</p>
👍

2018-03-13 09:25 UTC, noveogroup-amorgunov commented on views/partials/weather.hbs
> +        </article>
Нужно выводить город в котором сейчас такая погода

2018-03-13 09:25 UTC, noveogroup-amorgunov commented on views/category.hbs
> +    <h1 class="pageName">{{ title }}</h1>
нужна ссылка "Вернуться на главную"

2018-03-14 05:45 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-03-14 06:10 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-03-14 06:34 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-03-14 07:34 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-03-14 07:47 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-03-14 07:50 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-14 08:41 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-14 08:49 UTC, NurievMikhail commented on controllers/category.js
> +const NewsArticle = require('../models/news-article');
Боялся, что может возникнуть путаница с единственным и множественным числами

2018-03-14 09:34 UTC, noveogroup-amorgunov commented
@NurievMikhail  сделай просто порт по умолчанию

2018-03-14 14:34 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-14 17:00 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-14 20:27 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-15 04:00 UTC, noveogroup-amorgunov commented
@NurievMikhail напиши как можно будет смотреть

2018-03-15 04:49 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-15 05:04 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-15 05:10 UTC, NurievMikhail commented
@noveogroup-amorgunov Думаю, что можно смотреть, если Вы разрешите оставить в этом задании request, а axios попробовать в следующих домашках.

2018-03-15 05:44 UTC, noveogroup-amorgunov requested changes
Все круто, давай добьем пару мелких неточностей и я апрувлю пул реквест.

На счет axios, окей. Но в дальнейших проектах сменить request на более крутую либу стоит.

Сейчас можно не править, но на будущее: посмотреть у других ребят как правильно делать layout. Ты сейчас получается просто head и footer секции вынес в подшаблоны. А лайут поразумевает вынос в отдельный файл всего, кроме содержимого body.

2018-03-15 05:44 UTC, noveogroup-amorgunov commented on README.md
> -![Ilon](https://user-images.githubusercontent.com/7279995/36676329-33914366-1b2d-11e8-97c2-ddb54124747b.jpg)
Отличное readme, молодец!

2018-03-15 05:44 UTC, noveogroup-amorgunov commented on .gitignore
> +.env
👍

2018-03-15 05:44 UTC, noveogroup-amorgunov commented on config.js
> +    key: process.env.NEWSAPI_KEY,
key -> newsKey - а то не ясно, к чему этот ключ относится

2018-03-15 05:44 UTC, noveogroup-amorgunov commented on config.js
> +        { href: '../business', categoryName: 'Бизнес' },
href - это для ссылок в шаблоне, давай придумаем более общее название (key, slug или на подобии этого) и из значений уберем `../`, чтобы категории можно было переиспользовать в других местах, если понадобятся их ключи (а `../` просто добавим в шаблонах):
```
categories: [
    { key: 'business', categoryName: 'Бизнес' },
]
```

2018-03-15 05:44 UTC, noveogroup-amorgunov commented on config.js
> +        { href: '../business', categoryName: 'Бизнес' },
И это можно не делать, но на будущее удобно оформлять конфиг в виде подмодулей: https://github.com/urfu-2017/webdev-task-1/pull/21#discussion_r174359705

2018-03-15 05:44 UTC, noveogroup-amorgunov commented on controllers/news.js
> +};
```js
exports.list = async (req, res) => {
    const { country } = req.query;
    const { category } = req.params;
    const news = await NewsArticle.findAll({ category, country });

    res.render('category', Object.assign(res.locals, { news });
}
```
стилистика, можно не менять

2018-03-15 05:44 UTC, noveogroup-amorgunov commented on middlewares/handleErrors.js
> +    const port = config.port || 8080;
я думаю тут порт не нужен)

2018-03-15 05:44 UTC, noveogroup-amorgunov commented on middlewares/setInitialData.js
> +        res.locals.weathers = weathers;
```js
const { lat, lon, query: queryCountry  } = req.query;
const weathers = await Weather.findAll({ queryCountry, lat, lon });
res.locals.weathers = weathers;
```
И queryCity наверно правильней будет?

2018-03-15 05:44 UTC, noveogroup-amorgunov commented on .gitignore
> +.env
Создай файлик `.env.sample` c содержимым:
```
NEWSAPI_KEY=
```

Если будет много переменных окружений, их не придется запоминать, если будет файлик с ключами пемеренных

2018-03-15 07:29 UTC, NurievMikhail commented on middlewares/handleErrors.js
> +    const port = config.port || 8080;
Я его использую на странице error для ссылки на главную

2018-03-15 07:41 UTC, noveogroup-amorgunov commented on middlewares/handleErrors.js
> +    const port = config.port || 8080;
`<a href="http://localhost:{{ port }}">Перейти на главную</a>` исправь просто на `<a href="/">..</a>`

2018-03-15 07:42 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-15 07:44 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-15 07:45 UTC, NurievMikhail commented on middlewares/handleErrors.js
> +    const port = config.port || 8080;
Точно, спасибо

2018-03-15 08:03 UTC, noveogroup-amorgunov approved these changes

2018-03-15 08:04 UTC, closed without merging