Леонид Мелкозёров
urfu-2017/webdev-task-1 pull request #36
Opened 2018-03-08 13:06 UTC by danmerus

первая версия без погоды и бэма

2018-03-08 13:07 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-03-08 13:51 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-03-08 14:21 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-08 14:28 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-14 05:05 UTC, noveogroup-amorgunov requested changes
Нужно доделать виджет с погодой, привести стили в соответсвии с методологий бэм. Посмотри проекты других ребят. После того, как доделаешь, напиши сюда, я посмотрю

2018-05-07 18:29 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-05-07 18:54 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-05-07 19:08 UTC, danmerus commented
@plotnikovn что то тут понажимал, но задачу кажется доделал (npm test проходит локально)
 в третьей что то ещё нужно доделать?

2018-05-10 08:15 UTC, plotnikovn reviewed
что-то контент у карточки без описания смещается к центру

🍅

2018-05-10 08:15 UTC, plotnikovn commented on public/css/styles.css
> +    min-height: 100vh;
подвал не влезает, приходится скроллить

2018-05-10 08:15 UTC, plotnikovn commented on package.json
> +    "newsapi": "^2.2.0"
`got` потерял

2018-05-10 10:38 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-05-10 10:40 UTC, danmerus commented
@plotnikovn done

2018-05-10 10:49 UTC, plotnikovn reviewed
🍅

2018-05-10 10:49 UTC, plotnikovn commented on public/css/styles.css
> +    min-height: 95vh;
используй `calc()`, у тебя подвал фиксированной высоты

2018-05-10 11:12 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-05-10 11:45 UTC, closed without merging