Гусаров Вадим
urfu-2017/webdev-task-1 pull request #37
Opened 2018-03-08 14:59 UTC by gus1234

2018-03-08 14:59 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-03-08 15:13 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-03-08 15:15 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-03-09 09:18 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-03-10 06:55 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-10 06:56 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-12 11:02 UTC, Superilya requested changes

2018-03-12 11:02 UTC, Superilya commented on models/news.js
> +    }).then(response => {
зачем then? Сделал `const rewsponse = await newsapi.v2.topHeadlines()` и потом нормально синхронно обрабатывай свои данные

2018-03-12 11:02 UTC, Superilya commented on models/news.js
> +            element.publishedAt = element.publishedAt.slice(0, 10) +
такая мутация массива плохо, лучше юзнуть map, он сделает новый массив, зато семантически правильно, а оптимизации это второе

2018-03-12 11:02 UTC, Superilya commented on models/weather.js
> +        .then(function (response) {
тоже самое про then

2018-03-12 11:02 UTC, Superilya commented on models/weather.js
> +    const subOptions = await rp(options)
надо ~~взять нормальный node-fetch~~ выбрать что то одно между rp и request

2018-03-12 11:02 UTC, Superilya commented on models/weather.js
> +    const dataWeather = await rp(subOptions).then(function (subResponse) {
подзапросы должны разруливаться на уровне await это должен быть "синхронный" код

2018-03-12 11:02 UTC, Superilya commented on models/news.js
> +const NewsAPI = require('newsapi');
нифига ты хитрый) ну хорошо

2018-03-12 11:02 UTC, Superilya commented on public/css/main.css
> +html {
что за кодстайл такой?
```
body
{
    margin: 0 0;
}
```

2018-03-12 11:02 UTC, Superilya commented on public/news/css/main.css
> +  .categories__link {
ну это ж нечитаемо, если копировал откуда то, то юзни http://csscomb.com/online

2018-03-12 11:02 UTC, Superilya commented on controllers/controller.js
> +    const dataMain = JSON.parse(fs.readFileSync('./public/data.json'));
в продакшн бы такое не пустили, синхронные операции в рантайме зло, для примера ещё ок, но и тут можно вынести из функции, что бы данные считались при запуске сервера и потом просто подкидывались в render

2018-03-12 11:04 UTC, Superilya commented
С mvc всё не плохо, переделай главное асинхронщину нормально на async/await, ну и мелочи всякие.

2018-03-12 12:36 UTC, gus1234 commented on models/news.js
> +const NewsAPI = require('newsapi');
это, вроде , не запрещалось)

2018-03-12 12:38 UTC, gus1234 commented on public/css/main.css
> +html {
@Superilya ну у body есть margin'ы, я их убрал) плохо?

2018-03-12 12:45 UTC, gus1234 commented on public/news/css/main.css
> +  .categories__link {
не копировал ниоткуда ничего :-/

2018-03-13 17:47 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-13 17:48 UTC, gus1234 commented
@Superilya пофикшено.

2018-03-14 16:00 UTC, Superilya commented on public/news/css/main.css
> +  .categories__link {
ну в плане, я не про то что ты списал, а может из какого нибудь визуального редактора, взял boilerplate, всё ок

2018-03-14 16:06 UTC, Superilya commented
забыл request в package.json, а так не плохо

2018-03-14 16:06 UTC, closed without merging