Борзов Артём
urfu-2017/webdev-task-1 pull request #39
Opened 2018-03-08 19:39 UTC by Qoter

2018-03-08 19:42 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-03-08 19:44 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-03-08 19:50 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-12 11:16 UTC, Superilya requested changes

2018-03-12 11:16 UTC, Superilya commented on .eslintrc
> +            "experimentalObjectRestSpread": true
👍

2018-03-12 11:16 UTC, Superilya commented on middlewares/weather.js
> +    if (req.query.query) {
зачем эта логика в middleware? вынеси её нормально в контроллер он для этого и нужен. Если тебе надо переиспользовать код делай базовую модель, от неё наследуйся и переиспользуй сколько угодно

2018-03-12 11:16 UTC, Superilya commented on models/news.js
> +        }).then(res => res.articles)
это 🎩, надо юзать async/await

2018-03-12 11:16 UTC, Superilya commented on middlewares/weather.js
> +    if (req.query.query) {
или базовый контроллер. Использовать модели в мидлваре нельзя

2018-03-12 11:16 UTC, Superilya commented on models/weather.js
> +            .then(res => res.consolidated_weather)
зачем делать then, есть есть async/await 🤷‍♀️

2018-03-12 11:16 UTC, Superilya commented on public/categories.css
> +.categories {
хороший тон, прогнать svg через svgo, лучше делать это при сборке проекта. Кароч тебе надо знать что svg надо обрабатывать перед отправкой клиенту, если нет автоматизации для . этого придётся сделать это руками

2018-03-12 16:19 UTC, Superilya commented on models/weather.js
> +    constructor(city, temp, windSpeed, date, weatherStateAbbr) { // eslint-disable-line max-params
max-params не просто так, может подумать над тем, что бы переделать на один объект типа options?

2018-03-12 16:24 UTC, Superilya commented on models/weather.js
> +class Weather {
очень странный класс, это какой то паттерн? почему в loadConsolidated не вернуть просто объекты а надо возвращать инстансы самого себя? очень не явная логика

2018-03-12 20:58 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-03-13 05:18 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-03-13 06:57 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-03-13 07:11 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-13 07:12 UTC, Qoter commented on middlewares/weather.js
> +    if (req.query.query) {
Выпилил)

2018-03-13 07:12 UTC, Qoter commented on public/categories.css
> +.categories {
Прогнал)

2018-03-13 07:15 UTC, Qoter commented on models/weather.js
> +class Weather {
Ну логично, что статический метод загружающий погоду, возвращает инстансы погоды.
Если, например, апи поменяется, то не придётся менять все использования.

2018-03-14 16:31 UTC, Superilya commented on models/weather.js
> +const API_URI = 'https://www.metaweather.com/api/';
у тебя ж есть конфиг почему не унёс туда?

2018-03-14 16:32 UTC, closed without merging