Сайпиев Анвар
urfu-2017/webdev-task-1 pull request #46
Opened 2018-03-11 19:00 UTC by whoe

2018-03-11 19:00 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-03-11 19:28 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-18 07:38 UTC, mokhov reviewed
Не понятно почему местами ты юзаешь Stylus, а местами CSS?

2018-03-18 07:38 UTC, mokhov commented on .vscode/launch.json
> +{
Добавь папку `.vscode` в `.gitignore`, мне ни к чему эти файлы

2018-03-18 07:38 UTC, mokhov commented on controllers/home.js
> +    Object.assign(data, generic);
`Object.assign` поддерживает множество `sources` https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign

2018-03-18 07:38 UTC, mokhov commented on controllers/news.js
> +    data.toHomeVisible = true;
Почему это не написать при создании `data`

2018-03-18 07:38 UTC, mokhov commented on controllers/news.js
> +    const country = req.query.country === undefined ? 'ru' : req.query.country;
`const country = req.query.country || 'ru'`

2018-03-18 07:38 UTC, mokhov commented on models/news.js
> +class NewsModel {
Зачем нужен класс с единственным методом?

2018-03-18 07:38 UTC, mokhov commented on public/css/header.css
> +.header__toHome {
В БЭМ именовании надо писать `.header__to-home`

2018-03-18 07:38 UTC, mokhov commented on public/css/header.css
> +  line-height: 45px;
Очень странный конфликт со следующим свойством

2018-03-18 07:39 UTC, mokhov requested changes

2018-03-18 07:39 UTC, mokhov commented on widgets/weather.js
> +            `/static/img/weather/${nowWeather.weather_state_abbr}.svg`;
такие урлы лучше в конфиг выносить

2018-03-18 07:39 UTC, mokhov commented on widgets/weather.js
> +class WeatherWidget {
Внезапно практически нормальная модель здесь, но почему?!?!

2018-03-18 18:46 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-18 19:00 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-18 19:02 UTC, whoe commented on models/news.js
> +class NewsModel {
Кто то говорил что модель это обычно класс. К тому же из названия класса видно, что код относится к модели.

2018-03-18 19:08 UTC, whoe commented on controllers/news.js
> +    data.toHomeVisible = true;
Потому что assign(data, header) переопределит поле toHomeVisible

2018-03-18 19:35 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-20 04:21 UTC, mokhov commented on models/news.js
> +class NewsModel {
У тебя метод это статический должен быть

2018-03-20 04:21 UTC, mokhov commented on models/news.js
> +class NewsModel {
Ну и `Model` в названии лишнее

2018-03-20 09:58 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-04-04 04:58 UTC, closed without merging